export const actionFilterList = {
  COLOR: 'COLOR',
  COLOR_REMOVE: 'COLOR_REMOVE',
  COLOR_ENTER: 'COLOR_ENTER',
  COLOR_LEAVE: 'COLOR_LEAVE',
  COLOR_UP: 'COLOR_UP',
  COLOR_DOWN: 'COLOR_DOWN',
  REVERSE: 'REVERSE',
  ERASE: 'ERASE'
}